spring:
  application:
    name: cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenzeweishare/miaosha-parent.git                  # 配置Git仓库的地址
          search-paths: miaosha-config-repo
server:
  port: 8763
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/  #将自己8761注册到8762上

# 配置日志级别，让hibernate打印出执行的SQL
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    org.springframework.orm.jpa: INFO       #事务日志
    org.springframework.transaction: INFO   #事务日志
# 参考文档：http://projects.spring.io/spring-cloud/docs/1.0.3/spring-cloud.html#_standalone_mode
# 参考文档：http://my.oschina.net/buwei/blog/618756

